### ISSUE TITLE
Feedback Cancel Should Not Be Same As Never

### ISSUE THREAD

**Issue by berkayturanci** [codemybrainsout/smart-app-rate#30]
https://github.com/codemybrainsout/smart-app-rate/blob/5ba92099b55aef765f98cc0b2049c1aebcf54472/ratingdialog/src/main/java/com/codemybrainsout/ratingdialog/RatingDialog.java#L175

Cancel should not be the same as never in here. Cancel is the same thing that user clicked outside or back button. Or maybe user want to cancel for this time only.

**Comment by alexjcrowley** [comment]
The line you have linked to is in the "view.getId() == R.id.dialog_rating_button_feedback_submit" branch of the if-else system. 

The branch "view.getId() == R.id.dialog_rating_button_feedback_cancel" only calls dismiss()

Sorry if I am not seeing the issue here, if I am incorrect could you point to the issue?

Thanks!

**Comment by berkayturanci** [comment]
Hi @alexjcrowley in `R.id.dialog_rating_button_feedback_submit` part, cancel should be considered as only `dismiss` in my view point. Since user could not know if its show never or not. The problem is here both `dismiss` and `showNever` is called in here. We have to show to the user "never" for only  show never option, otherwise it could lead a misunderstandings for user.

**Comment by alexjcrowley** [comment]
@berkayturanci I believe showNever() is called because when the user has submitted the feedback because that means they did the rating and feedback, so asking them to rate again in future may become annoying. For example if I gave your app 3 stars and then it asked for feedback and I gave some it would be annoying to be asked again to rate in future. 

If the current functionality doesn't meet your requirements you could always branch off and make a version that does.

Thanks!

**Comment by berkayturanci** [comment]
My misunderstanding, I thought it was the cancel button in the feedback part. Never mind all of these :), sorry.
